#!/usr/bin/env bash
# Generate packaging/aur/iptv-tui-bin/{PKGBUILD,.SRCINFO}.
#
# Checksums come from a SHA256SUMS file when SUMS is set (CI passes the one from
# the release), otherwise they are computed from the local dist/ assets (run
# `make release/build VERSION=x.y.z` first).
set -euo pipefail

ver="${1:?usage: gen-pkgbuild.sh <version, e.g. 1.3.0>}"
root="$(cd "$(dirname "$0")/../.." && pwd)"
dist="${OUT:-$root/dist}"
out="$root/packaging/aur/iptv-tui-bin"
mkdir -p "$out"

# sha_of <asset-filename>: read from $SUMS if provided, else hash dist/<file>.
sha_of() {
	if [ -n "${SUMS:-}" ] && [ -f "$SUMS" ]; then
		grep " $1\$" "$SUMS" | awk '{print $1}' | head -1
	else
		[ -f "$dist/$1" ] || { echo "missing $dist/$1, run: make release/build VERSION=$ver" >&2; exit 1; }
		sha256sum "$dist/$1" | awk '{print $1}'
	fi
}

amd_sha="$(sha_of iptv-tui_linux_amd64)"
arm_sha="$(sha_of iptv-tui_linux_arm64)"
man_sha="$(sha_of iptv-tui.1)"
lic_sha="$(sha_of LICENSE)"

for v in "$amd_sha" "$arm_sha" "$man_sha" "$lic_sha"; do
	[ -n "$v" ] || { echo "could not resolve a checksum (SUMS=$SUMS)" >&2; exit 1; }
done

desc="IPTV TUI, a terminal UI to browse free IPTV playlists (iptv-org, Free-TV) by country or category and play them (prebuilt binary)"

cat >"$out/PKGBUILD" <<EOF
# Maintainer: Kinn Coelho Juliao <kinncj@gmail.com>
# Generated by packaging/aur/gen-pkgbuild.sh; do not edit by hand.
pkgname=iptv-tui-bin
pkgver=${ver}
pkgrel=1
pkgdesc="${desc}"
arch=('x86_64' 'aarch64')
url="https://github.com/kinncj/IPTV-TUI"
license=('MIT')
provides=('iptv-tui')
conflicts=('iptv-tui')
optdepends=('mpv: inline terminal playback and best HLS support'
            'vlc: alternate external player'
            'ffmpeg: built-in inline video player, and ffplay')
source=("iptv-tui_\${pkgver}.1::https://github.com/kinncj/IPTV-TUI/releases/download/v\${pkgver}/iptv-tui.1"
        "iptv-tui_\${pkgver}.LICENSE::https://github.com/kinncj/IPTV-TUI/releases/download/v\${pkgver}/LICENSE")
sha256sums=('${man_sha}'
            '${lic_sha}')
source_x86_64=("iptv-tui_\${pkgver}_x86_64::https://github.com/kinncj/IPTV-TUI/releases/download/v\${pkgver}/iptv-tui_linux_amd64")
source_aarch64=("iptv-tui_\${pkgver}_aarch64::https://github.com/kinncj/IPTV-TUI/releases/download/v\${pkgver}/iptv-tui_linux_arm64")
sha256sums_x86_64=('${amd_sha}')
sha256sums_aarch64=('${arm_sha}')

package() {
    install -Dm755 "\${srcdir}/iptv-tui_\${pkgver}_\${CARCH}" "\${pkgdir}/usr/bin/iptv-tui"
    install -Dm644 "\${srcdir}/iptv-tui_\${pkgver}.1" "\${pkgdir}/usr/share/man/man1/iptv-tui.1"
    install -Dm644 "\${srcdir}/iptv-tui_\${pkgver}.LICENSE" "\${pkgdir}/usr/share/licenses/\${pkgname}/LICENSE"
}
EOF

cat >"$out/.SRCINFO" <<EOF
pkgbase = iptv-tui-bin
	pkgdesc = ${desc}
	pkgver = ${ver}
	pkgrel = 1
	url = https://github.com/kinncj/IPTV-TUI
	arch = x86_64
	arch = aarch64
	license = MIT
	provides = iptv-tui
	conflicts = iptv-tui
	optdepends = mpv: inline terminal playback and best HLS support
	optdepends = vlc: alternate external player
	optdepends = ffmpeg: built-in inline video player, and ffplay
	source = iptv-tui_${ver}.1::https://github.com/kinncj/IPTV-TUI/releases/download/v${ver}/iptv-tui.1
	sha256sums = ${man_sha}
	source = iptv-tui_${ver}.LICENSE::https://github.com/kinncj/IPTV-TUI/releases/download/v${ver}/LICENSE
	sha256sums = ${lic_sha}
	source_x86_64 = iptv-tui_${ver}_x86_64::https://github.com/kinncj/IPTV-TUI/releases/download/v${ver}/iptv-tui_linux_amd64
	sha256sums_x86_64 = ${amd_sha}
	source_aarch64 = iptv-tui_${ver}_aarch64::https://github.com/kinncj/IPTV-TUI/releases/download/v${ver}/iptv-tui_linux_arm64
	sha256sums_aarch64 = ${arm_sha}

pkgname = iptv-tui-bin
EOF

echo "wrote:"
echo "  $out/PKGBUILD"
echo "  $out/.SRCINFO"
