#!/usr/bin/env bash
# Generate packaging/aur/iptv-tui-bin/{PKGBUILD,.SRCINFO} from the release
# assets in dist/ (run `make release VERSION=x.y.z` first). Mirrors the flow
# used for heimdall-hub-bin.
set -euo pipefail

ver="${1:?usage: gen-pkgbuild.sh <version, e.g. 1.3.0>}"
root="$(cd "$(dirname "$0")/../.." && pwd)"
dist="$root/dist"
out="$root/packaging/aur/iptv-tui-bin"
mkdir -p "$out"

amd="$dist/iptv-tui_linux_amd64"
arm="$dist/iptv-tui_linux_arm64"
man="$dist/iptv-tui.1"
for f in "$amd" "$arm" "$man"; do
	[ -f "$f" ] || { echo "missing $f — run: make release VERSION=$ver" >&2; exit 1; }
done

sha() { sha256sum "$1" | awk '{print $1}'; }
amd_sha="$(sha "$amd")"
arm_sha="$(sha "$arm")"
man_sha="$(sha "$man")"

cat >"$out/PKGBUILD" <<EOF
# Maintainer: Kinn Coelho Juliao <kinncj@gmail.com>
# Generated by packaging/aur/gen-pkgbuild.sh — do not edit by hand.
pkgname=iptv-tui-bin
pkgver=${ver}
pkgrel=1
pkgdesc="IPTV TUI — browse free IPTV playlists (iptv-org, Free-TV) by country/category and play them (prebuilt binary)"
arch=('x86_64' 'aarch64')
url="https://github.com/kinncj/iptv"
license=('AGPL-3.0-or-later')
provides=('iptv-tui')
conflicts=('iptv-tui')
optdepends=('mpv: inline terminal playback and best HLS support'
            'vlc: alternate external player'
            'ffmpeg: ffplay fallback player')
source=("iptv-tui_\${pkgver}.1::https://github.com/kinncj/iptv/releases/download/v\${pkgver}/iptv-tui.1")
sha256sums=('${man_sha}')
source_x86_64=("iptv-tui_\${pkgver}_x86_64::https://github.com/kinncj/iptv/releases/download/v\${pkgver}/iptv-tui_linux_amd64")
source_aarch64=("iptv-tui_\${pkgver}_aarch64::https://github.com/kinncj/iptv/releases/download/v\${pkgver}/iptv-tui_linux_arm64")
sha256sums_x86_64=('${amd_sha}')
sha256sums_aarch64=('${arm_sha}')

package() {
    install -Dm755 "\${srcdir}/iptv-tui_\${pkgver}_\${CARCH}" "\${pkgdir}/usr/bin/iptv-tui"
    install -Dm644 "\${srcdir}/iptv-tui_\${pkgver}.1" "\${pkgdir}/usr/share/man/man1/iptv-tui.1"
}
EOF

cat >"$out/.SRCINFO" <<EOF
pkgbase = iptv-tui-bin
	pkgdesc = IPTV TUI — browse free IPTV playlists (iptv-org, Free-TV) by country/category and play them (prebuilt binary)
	pkgver = ${ver}
	pkgrel = 1
	url = https://github.com/kinncj/iptv
	arch = x86_64
	arch = aarch64
	license = AGPL-3.0-or-later
	provides = iptv-tui
	conflicts = iptv-tui
	optdepends = mpv: inline terminal playback and best HLS support
	optdepends = vlc: alternate external player
	optdepends = ffmpeg: ffplay fallback player
	source = iptv-tui_${ver}.1::https://github.com/kinncj/iptv/releases/download/v${ver}/iptv-tui.1
	sha256sums = ${man_sha}
	source_x86_64 = iptv-tui_${ver}_x86_64::https://github.com/kinncj/iptv/releases/download/v${ver}/iptv-tui_linux_amd64
	sha256sums_x86_64 = ${amd_sha}
	source_aarch64 = iptv-tui_${ver}_aarch64::https://github.com/kinncj/iptv/releases/download/v${ver}/iptv-tui_linux_arm64
	sha256sums_aarch64 = ${arm_sha}

pkgname = iptv-tui-bin
EOF

echo "wrote:"
echo "  $out/PKGBUILD"
echo "  $out/.SRCINFO"
